apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: spring-sensors-publisher
spec:
  builder:
    kind: ClusterBuilder
    name: default
  cache:
    volume:
      size: 2G
  failedBuildHistoryLimit: 10
  imageTaggingStrategy: BuildNumber
  serviceAccountName: default
  source:
    git:
      revision: 32c7fc8cec31bc674531df17fec8ea1bbeff26a8
      url: https://github.com/tanzu-end-to-end/spring-sensors-sensor
  successBuildHistoryLimit: 10
  tag: index.docker.io/springdeveloper/spring-sensors-publisher:latest
